cloudgate:
  required_version: '~> 4.0.0'

app:
  name: peerbin
  environment: dev
  deploy_group: PeerBinDeployUsers
  region: us-west-2
  vpc_cluster: inseng-dev

  users:
    brianp:
      name: Brian Palmer
      email: brianp@instructure.com
      ssh_key: ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAtCPFMhCL/4Zb69MZlsndONJD68TOTHs3J+V00rLbsAcQhRDMFpweRBk5cl2bos8aMpUSBOSl+NQ6pMKWrAJwcheKZjrRqsQEx/uTN8oY5znQ7W2l9S1L/0jTjPP2xoaZaeKRUq3bkhxy9mzao1YLn1FOv9+QQMcBhLeSnUWB7otTRzqt5lk6YkWxZ6iSgMtfWhauKy1KWeYvRnB+HYyfDRn74eRaN33CfUDZqb0ZzS6vBXQOH90svSQaPsIcCVj/U0sPWyv31zeZMdKCZZL9WVLwL8dQeafSKOzOSp3bRNGVKv6veQsTi7a5o3LuvCfVAWvYbXVdRDRsHxYVGZBSSw==

  instance_pools:
    web:
      flavor: web
      instance_type: m4.large
      min_size: 1
      max_size: 1
      health_check_path: '/health_check'
      http_port: 80
      https_port: 80
      env_vars:
        NGINX_WORKER_COUNT: '1'
        PASSENGER_MAX_POOL_SIZE: '1'

  load_balancers:
    web:
      ssl_cert_arn: "arn:aws:iam::830473435438:server-certificate/star.inseng.net_20190620"
